# Generated by Django 5.1.2 on 2024-10-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_parcial',
            field=models.IntegerField(default='0', max_length=128),
            preserve_default=False,
        ),
    ]
