# Generated by Django 5.1.2 on 2024-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pedido_usuario_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='correo',
            field=models.EmailField(max_length=128),
        ),
    ]
